# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

# edit here triggers, cf. https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml
trigger:
- master
pr:
  autoCancel: true
  branches:
    include:
    - master

# For now, run CI only for Ubuntu 20.04.
# Could run for MacOS as well. Probably a good idea at some point.
# check software list for Ubuntu 20.04 here: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
pool:
  vmImage: 'ubuntu-20.04'
jobs:
  - job: 'tuplex'
    timeoutInMinutes: 180
    steps:
      # MongoDB should be already installed...
      #- script: sudo bash scripts/ubuntu2004/install_mongodb.sh
      #  displayName: 'Install MongoDB'
      # setup required MongoDB, Azure image comes with MongoDB 5.0.6 preinstalled
      - script: sudo bash scripts/ubuntu2004/install_reqs.sh
        displayName: 'Install required packages'
      - script: sudo apt-get install -y python3-setuptools ninja-build && sudo python3 -m pip install pytest pygments>=2.4.1 pexpect setuptools astor PyYAML jupyter nbformat pymongo eventlet==0.30.0 gunicorn pymongo && jupyter --version
        displayName: 'Install python dependencies'
      - script: TUPLEX_BUILD_ALL=1 CMAKE_ARGS="-DBUILD_WITH_ORC=ON -DLLVM_ROOT_DIR=/usr/lib/llvm-9 -DCMAKE_BUILD_TYPE=Release -DBUILD_FOR_CI=ON" python3 setup.py install --user
        displayName: 'Build Tuplex'
      - script: cd build/temp.linux-x86_64-3.8 && ctest --timeout 180 --output-on-failure
        displayName: 'C++ tests'
      - script: cd build/temp.linux-x86_64-3.8/dist/python && python3.8 -m pytest -x --full-trace -l --log-cli-level debug
        displayName: 'Python tests'
